import { store } from './store.js';

export const STRINGS = {
  en:{
    tab_home:'Home',tab_stats:'Stats',tab_train:'Train',tab_dungeons:'Dungeons',tab_gear:'Gear',tab_shop:'Shop',tab_log:'History',
    ph_character:'Character',ph_weekly_quest:'Weekly Quest',ph_data:'Data',ph_combat_stats:'Combat Stats',ph_base_stats:'Base Stats',ph_gear_contribution:'Gear Contribution',ph_abilities:'Abilities Unlocked',ph_level_progress:'Level Progression',ph_templates:'Session Templates',ph_train:'Log a Training Session',ph_dungeons:'Trials of the Depths',ph_equipped:'Equipped',ph_inventory:'Inventory',ph_shop:"Merchant's Stall",ph_shop_equipped:'Currently Equipped',ph_history:'Chronicles',ph_pending:'Planned Sessions',ph_blacksmith:'Blacksmith',
    lbl_experience:'Experience',lbl_stamina:'Stamina',lbl_strength:'Strength',lbl_dexterity:'Dexterity',lbl_vitality:'Vitality',lbl_body_weight:'Body Weight',lbl_bw_hint:'kg — used for bodyweight exercises',lbl_gold:'GOLD',lbl_streak:'STREAK',lbl_sessions:'SESSIONS',
    btn_add_exercise:'+ Add Exercise',btn_save_template:'Save as Template',btn_plan_session:'📋 Plan Session',btn_complete_session:'⚔ Complete Session',btn_load:'Load',btn_delete:'Delete',btn_export:'Export Save',btn_import:'Import Save',btn_force_reload:'Force Reload',btn_reset:'Reset Game',btn_delete_account:'Delete Account',btn_sign_in:'Sign In',btn_create_account:'Create Account',btn_play_local:'Play Locally',btn_back:'← Back',btn_sound_on:'Sound: On',btn_sound_off:'Sound: Off',btn_sync:'Sync',btn_sign_out:'Sign Out',btn_refresh:'Refresh',
    save_local:'Your progress is saved locally. Sign in to sync across devices.',save_cloud:'Progress saved locally and to cloud.',
    templates_empty:'No saved templates yet. Build a session below and save it.',
    ex_label:'EXERCISE',ex_exercise:'Exercise',ex_weight:'Weight (kg)',ex_reps:'Reps',ex_sets:'Sets',ex_run_suffix:'(Run)',ex_activity_suffix:'(Activity)',
    dungeon_stamina:'STAMINA',dungeon_cost:'COST:',dungeon_cleared:'Cleared',dungeon_locked:'Locked',dungeon_low_stamina:'Low Stamina',dungeon_enter:'Enter',dungeon_trial:'TRIAL',
    inv_empty:'Your pack is empty.',inv_equip:'Equip',inv_sell:'Sell',shop_empty:'Sold out! Check next Monday.',shop_hint:'Only normal wares — rares drop from trials.',blacksmith_hint:'Spend gold to permanently upgrade a stat on any item you own. Each upgrade on that item costs more than the last.',blacksmith_empty:'Own or equip an item to upgrade it here.',lbl_equipped_badge:'EQUIPPED',
    history_empty:'No sessions recorded yet.',
    hist_pick_exercise:'Exercise',hist_col_date:'Date',hist_col_volume:'Volume',hist_col_distance:'Distance (km)',hist_col_duration:'Duration (min)',hist_no_baseline:'first record',
    levelup_title:'LEVEL UP',levelup_dismiss:'— Continue your journey —',combat_title:'TRIAL',combat_you:'You',reward_title:'SESSION COMPLETE',reward_dismiss:'— Onward —',
    welcome_tagline:'Your training. Your legend.',welcome_desc:'Sign in to keep your progress and play across devices — or play locally on this device only.',welcome_auth_desc:'Sign in or create a free account.',welcome_name_ph:'Character Name',welcome_pass_ph:'Password (min. 6 characters)',
    stat_maxhp:'Max HP',stat_damage:'Damage Range',stat_crit:'Crit Chance',stat_reduction:'Damage Reduction',stat_stamina:'Stamina',stat_trials:'Trials Cleared',stat_earned:'Earned through training — permanent.',stat_gear_hint:'Gear bonuses add directly to your stats.',stat_before_defense:'before boss defense',stat_crit_mult:'damage',stat_from_vit:'from VIT',stat_max:'max',stat_dungeon_entry:'dungeon entry:',
    quest_desc:'Defeat {boss} — train on {n} separate days this week.',quest_reward:'Reward: {gold} Gold + {xp} XP',quest_completed:'✦ Completed — streak {n}',
    modal_cancel:'Cancel',modal_close:'Close',modal_save:'Save',modal_import_action:'Import',modal_delete_action:'Delete',modal_reset_all:'Reset Everything',modal_delete_forever:'Delete Forever',
    modal_export_title:'Export Save',modal_export_body:'Copy this and store it safely.',modal_import_title:'Import Save',modal_import_body:'Paste your exported save. This overwrites current progress.',modal_reset_title:'Reset Game?',modal_reset_body:'This erases ALL progress. Export first if unsure.',modal_del_acc_title:'Delete Account?',modal_del_acc_body:'This permanently deletes your account and all cloud progress. This cannot be undone.',modal_save_tpl_title:'Save Template',modal_save_tpl_body:'Enter a name for this session template:',modal_del_tpl_title:'Delete Template?',modal_del_tpl_body:'This cannot be undone.',modal_discard_pending_title:'Discard Planned Session?',modal_discard_pending_body:'This cannot be undone.',modal_signin_title:'Sign In / Create Account',
    streak_hint:'Repeat an exercise within 7 days to earn a consistency bonus (+5% per week, up to ×1.50 max). Miss the 7-day window and the bonus resets to ×1.00.',
    toast_imported:'Save imported.',toast_invalid:'Invalid data.',toast_invalid_save:'Invalid save data.',toast_reset:'Game reset.',toast_shop_refresh:'Stock refreshed.',toast_cloud_loaded:'Cloud save loaded.',toast_signed_in:'Signed in.',toast_signed_out:'Signed out.',toast_account_deleted:'Account deleted.',toast_synced:'Synced to cloud.',toast_enter_credentials:'Enter character name and password.',toast_pass_short:'Password must be at least 6 characters.',toast_name_taken:'Character name already taken.',toast_tpl_saved:'Template saved.',toast_tpl_loaded:'Template loaded.',toast_tpl_deleted:'Template deleted.',toast_tpl_no_exercises:'Add at least one exercise first.',toast_tpl_no_name:'Enter a template name.',toast_invalid_name:'Invalid character name.',toast_created:'Account created! Signing you in...',toast_signin_fail:'Sign in failed: ',toast_signup_fail:'Sign up failed: ',toast_session_planned:'Session planned. Complete it later to bank your rewards.',toast_pending_discarded:'Planned session discarded.',reward_forge:'The forge accepts your effort.',reward_gold:'Gold',reward_streak_bonus:'Streak Bonus',reward_weekly_title:'WEEKLY QUEST COMPLETE',reward_weekly_falls:'{boss} falls before you!',reward_bonus_gold:'Bonus Gold',reward_bonus_xp:'Bonus XP',reward_streak:'Streak',reward_weeks:'weeks',inv_req_lvl:'Req lvl',stat_str_from:'STR from gear',stat_dex_from:'DEX from gear',stat_vit_from:'VIT from gear',stat_str_header:'STR — Strength',stat_dex_header:'DEX — Dexterity',stat_vit_header:'VIT — Vitality',stat_str_desc:'Each point adds <b>+1 damage</b> to your attacks. Built from heavy compound lifts — deadlifts, squats, bench press, rows, presses.',stat_dex_desc:'Each point adds +1 to maximum damage and increases critical hit chance on a curve that approaches 95% but never reaches it. Built from technical bodyweight work, pull-ups, dips, lunges, isolations.',stat_vit_desc:'Each point adds <b>+{hpPerVIT} max HP</b> and reduces incoming damage by a percentage (VIT÷(VIT+{vitDefenseK}), capped at {vitDefenseMax}%). Built from VIT exercises (farmer\'s walk, sled push) <i>or</i> any set of {vitRepThreshold}+ reps (earns 30% of that exercise\'s stat as VIT bonus).',ab_free:'Free',ab_stamina:'stamina',ab_unlocks_at:'Unlocks at Lvl',levelup_reached:'You have reached Level {level}.',levelup_new_ability:'New ability: {name}',combat_face_boss:'You face {boss}.',tooltip_equipped:'Equipped',tooltip_req_lv:'Req Lv',
  },
  cs:{
    tab_home:'Domov',tab_stats:'Statistiky',tab_train:'Trénink',tab_dungeons:'Dungeony',tab_gear:'Výbava',tab_shop:'Obchod',tab_log:'Historie',
    ph_character:'Postava',ph_weekly_quest:'Týdenní úkol',ph_data:'Data',ph_combat_stats:'Bojové statistiky',ph_base_stats:'Základní statistiky',ph_gear_contribution:'Příspěvek výbavy',ph_abilities:'Odemčené schopnosti',ph_level_progress:'Postup úrovní',ph_templates:'Šablony sezón',ph_train:'Zaznamenat trénink',ph_dungeons:'Zkoušky hlubin',ph_equipped:'Vybaveno',ph_inventory:'Inventář',ph_shop:'Kupecký stánek',ph_shop_equipped:'Aktuálně vybaveno',ph_history:'Kroniky',ph_pending:'Naplánované sezóny',ph_blacksmith:'Kovář',
    lbl_experience:'Zkušenosti',lbl_stamina:'Výdrž',lbl_strength:'Síla',lbl_dexterity:'Obratnost',lbl_vitality:'Vitalita',lbl_body_weight:'Tělesná hmotnost',lbl_bw_hint:'kg — pro cviky s vlastní vahou',lbl_gold:'ZLATO',lbl_streak:'SÉRIE',lbl_sessions:'SEZÓNY',
    btn_add_exercise:'+ Přidat cvičení',btn_save_template:'Uložit jako šablonu',btn_plan_session:'📋 Naplánovat sezónu',btn_complete_session:'⚔ Dokončit sezónu',btn_load:'Načíst',btn_delete:'Smazat',btn_export:'Exportovat uložení',btn_import:'Importovat uložení',btn_force_reload:'Obnovit',btn_reset:'Resetovat hru',btn_delete_account:'Smazat účet',btn_sign_in:'Přihlásit se',btn_create_account:'Vytvořit účet',btn_play_local:'Hrát lokálně',btn_back:'← Zpět',btn_sound_on:'Zvuk: Zapnuto',btn_sound_off:'Zvuk: Vypnuto',btn_sync:'Synchronizovat',btn_sign_out:'Odhlásit se',btn_refresh:'Obnovit',
    save_local:'Pokrok uložen lokálně. Přihlaste se pro synchronizaci.',save_cloud:'Pokrok uložen lokálně i v cloudu.',
    templates_empty:'Zatím žádné šablony. Sestavte sezónu níže a uložte ji.',
    ex_label:'CVIČENÍ',ex_exercise:'Cvičení',ex_weight:'Váha (kg)',ex_reps:'Opakování',ex_sets:'Série',ex_run_suffix:'(Běh)',ex_activity_suffix:'(Aktivita)',
    dungeon_stamina:'VÝDRŽ',dungeon_cost:'CENA:',dungeon_cleared:'Dokončeno',dungeon_locked:'Zamčeno',dungeon_low_stamina:'Nízká výdrž',dungeon_enter:'Vstoupit',dungeon_trial:'ZKOUŠKA',
    inv_empty:'Váš batoh je prázdný.',inv_equip:'Vybavit',inv_sell:'Prodat',shop_empty:'Vyprodáno! Zkontrolujte příští pondělí.',shop_hint:'Pouze běžné zboží — vzácné předměty padají ze zkoušek.',blacksmith_hint:'Utraťte zlato za trvalé vylepšení statistiky libovolného vlastněného předmětu. Každé další vylepšení stejného předmětu je dražší.',blacksmith_empty:'Vlastněte nebo vybavte předmět, abyste ho zde mohli vylepšit.',lbl_equipped_badge:'VYBAVENO',
    history_empty:'Zatím žádné sezóny zaznamenány.',
    hist_pick_exercise:'Cvičení',hist_col_date:'Datum',hist_col_volume:'Objem',hist_col_distance:'Vzdálenost (km)',hist_col_duration:'Doba (min)',hist_no_baseline:'první záznam',
    levelup_title:'POSTUP ÚROVNĚ',levelup_dismiss:'— Pokračujte ve své cestě —',combat_title:'ZKOUŠKA',combat_you:'Ty',reward_title:'SEZÓNA DOKONČENA',reward_dismiss:'— Vpřed —',
    welcome_tagline:'Váš trénink. Vaše legenda.',welcome_desc:'Přihlaste se a sledujte pokrok napříč zařízeními — nebo hrajte pouze lokálně.',welcome_auth_desc:'Přihlaste se nebo vytvořte bezplatný účet.',welcome_name_ph:'Jméno postavy',welcome_pass_ph:'Heslo (min. 6 znaků)',
    stat_maxhp:'Max HP',stat_damage:'Rozsah poškození',stat_crit:'Šance na krit',stat_reduction:'Snížení poškození',stat_stamina:'Výdrž',stat_trials:'Dokončené zkoušky',stat_earned:'Získáno tréninkem — trvalé.',stat_gear_hint:'Bonusy výbavy se přidávají přímo ke statistikám.',stat_before_defense:'před obranou bosse',stat_crit_mult:'poškození',stat_from_vit:'z VIT',stat_max:'max',stat_dungeon_entry:'vstup do dungeonu:',
    quest_desc:'Porazte {boss} — trénujte alespoň {n} různé dny v tomto týdnu.',quest_reward:'Odměna: {gold} zlata + {xp} ZK',quest_completed:'✦ Dokončeno — série {n}',
    modal_cancel:'Zrušit',modal_close:'Zavřít',modal_save:'Uložit',modal_import_action:'Importovat',modal_delete_action:'Smazat',modal_reset_all:'Resetovat vše',modal_delete_forever:'Smazat navždy',
    modal_export_title:'Exportovat uložení',modal_export_body:'Zkopírujte a uložte na bezpečné místo.',modal_import_title:'Importovat uložení',modal_import_body:'Vložte exportované uložení. Přepíše aktuální pokrok.',modal_reset_title:'Resetovat hru?',modal_reset_body:'Tím smažete VEŠKERÝ pokrok. Nejprve exportujte.',modal_del_acc_title:'Smazat účet?',modal_del_acc_body:'Trvale smaže váš účet a veškerý cloudový pokrok. Nelze vrátit.',modal_save_tpl_title:'Uložit šablonu',modal_save_tpl_body:'Zadejte název pro tuto šablonu sezóny:',modal_del_tpl_title:'Smazat šablonu?',modal_del_tpl_body:'Tuto akci nelze vrátit.',modal_discard_pending_title:'Zahodit naplánovanou sezónu?',modal_discard_pending_body:'Tuto akci nelze vrátit.',modal_signin_title:'Přihlásit se / Vytvořit účet',
    streak_hint:'Opakujte cvičení do 7 dnů a získejte bonus za pravidelnost (+5 % týdně, max ×1,50). Zmeškaný interval resetuje bonus zpět na ×1,00.',
    toast_imported:'Uložení importováno.',toast_invalid:'Neplatná data.',toast_invalid_save:'Neplatná data uložení.',toast_reset:'Hra resetována.',toast_shop_refresh:'Zásoby obnoveny.',toast_cloud_loaded:'Cloudové uložení načteno.',toast_signed_in:'Přihlášen.',toast_signed_out:'Odhlášen.',toast_account_deleted:'Účet smazán.',toast_synced:'Synchronizováno s cloudem.',toast_enter_credentials:'Zadejte jméno postavy a heslo.',toast_pass_short:'Heslo musí mít alespoň 6 znaků.',toast_name_taken:'Jméno postavy je již obsazeno.',toast_tpl_saved:'Šablona uložena.',toast_tpl_loaded:'Šablona načtena.',toast_tpl_deleted:'Šablona smazána.',toast_tpl_no_exercises:'Nejprve přidejte alespoň jedno cvičení.',toast_tpl_no_name:'Zadejte název šablony.',toast_invalid_name:'Neplatné jméno postavy.',toast_created:'Účet vytvořen! Přihlašování...',toast_signin_fail:'Přihlášení selhalo: ',toast_signup_fail:'Registrace selhala: ',toast_session_planned:'Sezóna naplánována. Dokončete ji později a získejte odměny.',toast_pending_discarded:'Naplánovaná sezóna zahozena.',reward_forge:'Oheň přijal vaše úsilí.',reward_gold:'Zlato',reward_streak_bonus:'Bonus za sérii',reward_weekly_title:'TÝDENNÍ ÚKOL DOKONČEN',reward_weekly_falls:'{boss} padá před vámi!',reward_bonus_gold:'Bonusové zlato',reward_bonus_xp:'Bonusové ZK',reward_streak:'Série',reward_weeks:'týdnů',inv_req_lvl:'Požad. úroveň',stat_str_from:'SÍL z výbavy',stat_dex_from:'OBR z výbavy',stat_vit_from:'VIT z výbavy',stat_str_header:'SÍL — Síla',stat_dex_header:'OBR — Obratnost',stat_vit_header:'VIT — Vitalita',stat_str_desc:'Každý bod přidává <b>+1 poškození</b> útokům. Budován z těžkých složených cviků — mrtvý tah, dřepy, bench press, veslování, tlaky.',stat_dex_desc:'Každý bod přidává +1 k max. poškození a zvyšuje šanci na krit. Budován z technické práce s vlastní vahou, přítahy, dipy, výpady, izolace.',stat_vit_desc:'Každý bod přidává <b>+{hpPerVIT} max HP</b> a snižuje poškození o procento (VIT÷(VIT+{vitDefenseK}), max {vitDefenseMax}%). Budován z VIT cviků nebo série s {vitRepThreshold}+ opakováními.',ab_free:'Zdarma',ab_stamina:'výdrže',ab_unlocks_at:'Odemyká se na úrovni',levelup_reached:'Dosáhli jste úrovně {level}.',levelup_new_ability:'Nová schopnost: {name}',combat_face_boss:'Čelíte {boss}.',tooltip_equipped:'Vybaveno',tooltip_req_lv:'Požad. úroveň',
  },
  pl:{
    tab_home:'Dom',tab_stats:'Statystyki',tab_train:'Trening',tab_dungeons:'Lochy',tab_gear:'Ekwipunek',tab_shop:'Sklep',tab_log:'Historia',
    ph_character:'Postać',ph_weekly_quest:'Tygodniowe zadanie',ph_data:'Dane',ph_combat_stats:'Statystyki bojowe',ph_base_stats:'Statystyki bazowe',ph_gear_contribution:'Wkład ekwipunku',ph_abilities:'Odblokowane zdolności',ph_level_progress:'Postęp poziomów',ph_templates:'Szablony sesji',ph_train:'Zaloguj sesję treningową',ph_dungeons:'Próby Głębin',ph_equipped:'Wyposażone',ph_inventory:'Ekwipunek',ph_shop:'Stragan kupca',ph_shop_equipped:'Aktualnie wyposażone',ph_history:'Kroniki',ph_pending:'Zaplanowane sesje',ph_blacksmith:'Kowal',
    lbl_experience:'Doświadczenie',lbl_stamina:'Wytrzymałość',lbl_strength:'Siła',lbl_dexterity:'Zręczność',lbl_vitality:'Witalność',lbl_body_weight:'Masa ciała',lbl_bw_hint:'kg — do ćwiczeń z masą ciała',lbl_gold:'ZŁOTO',lbl_streak:'SERIA',lbl_sessions:'SESJE',
    btn_add_exercise:'+ Dodaj ćwiczenie',btn_save_template:'Zapisz jako szablon',btn_plan_session:'📋 Zaplanuj sesję',btn_complete_session:'⚔ Zakończ sesję',btn_load:'Wczytaj',btn_delete:'Usuń',btn_export:'Eksportuj zapis',btn_import:'Importuj zapis',btn_force_reload:'Wymuś odświeżenie',btn_reset:'Resetuj grę',btn_delete_account:'Usuń konto',btn_sign_in:'Zaloguj się',btn_create_account:'Utwórz konto',btn_play_local:'Graj lokalnie',btn_back:'← Wróć',btn_sound_on:'Dźwięk: Włączony',btn_sound_off:'Dźwięk: Wyłączony',btn_sync:'Synchronizuj',btn_sign_out:'Wyloguj się',btn_refresh:'Odśwież',
    save_local:'Postęp zapisany lokalnie. Zaloguj się, aby synchronizować.',save_cloud:'Postęp zapisany lokalnie i w chmurze.',
    templates_empty:'Brak szablonów. Stwórz sesję poniżej i zapisz ją.',
    ex_label:'ĆWICZENIE',ex_exercise:'Ćwiczenie',ex_weight:'Ciężar (kg)',ex_reps:'Powtórzenia',ex_sets:'Serie',ex_run_suffix:'(Bieg)',ex_activity_suffix:'(Aktywność)',
    dungeon_stamina:'WYTRZYMAŁOŚĆ',dungeon_cost:'KOSZT:',dungeon_cleared:'Ukończono',dungeon_locked:'Zablokowano',dungeon_low_stamina:'Mała wytrzymałość',dungeon_enter:'Wejdź',dungeon_trial:'PRÓBA',
    inv_empty:'Twój plecak jest pusty.',inv_equip:'Załóż',inv_sell:'Sprzedaj',shop_empty:'Wyprzedano! Sprawdź w przyszły poniedziałek.',shop_hint:'Tylko zwykłe towary — rzadkie przedmioty wypadają z lochów.',blacksmith_hint:'Wydaj złoto, aby trwale ulepszyć statystykę dowolnego posiadanego przedmiotu. Każde kolejne ulepszenie tego samego przedmiotu kosztuje więcej.',blacksmith_empty:'Posiadaj lub załóż przedmiot, aby móc go tutaj ulepszyć.',lbl_equipped_badge:'ZAŁOŻONE',
    history_empty:'Brak zapisanych sesji.',
    hist_pick_exercise:'Ćwiczenie',hist_col_date:'Data',hist_col_volume:'Objętość',hist_col_distance:'Dystans (km)',hist_col_duration:'Czas (min)',hist_no_baseline:'pierwszy zapis',
    levelup_title:'AWANS POZIOMU',levelup_dismiss:'— Kontynuuj swoją podróż —',combat_title:'PRÓBA',combat_you:'Ty',reward_title:'SESJA ZAKOŃCZONA',reward_dismiss:'— Naprzód —',
    welcome_tagline:'Twój trening. Twoja legenda.',welcome_desc:'Zaloguj się, aby śledzić postęp na różnych urządzeniach — lub graj tylko lokalnie.',welcome_auth_desc:'Zaloguj się lub utwórz bezpłatne konto.',welcome_name_ph:'Nazwa postaci',welcome_pass_ph:'Hasło (min. 6 znaków)',
    stat_maxhp:'Max HP',stat_damage:'Zakres obrażeń',stat_crit:'Szansa na trafienie krytyczne',stat_reduction:'Redukcja obrażeń',stat_stamina:'Wytrzymałość',stat_trials:'Ukończone próby',stat_earned:'Zdobyte przez trening — trwałe.',stat_gear_hint:'Bonusy ekwipunku dodają się bezpośrednio do statystyk.',stat_before_defense:'przed obroną bossa',stat_crit_mult:'obrażeń',stat_from_vit:'z VIT',stat_max:'maks',stat_dungeon_entry:'wejście do lochu:',
    quest_desc:'Pokonaj {boss} — trenuj przez {n} różne dni w tym tygodniu.',quest_reward:'Nagroda: {gold} złota + {xp} PD',quest_completed:'✦ Ukończono — seria {n}',
    modal_cancel:'Anuluj',modal_close:'Zamknij',modal_save:'Zapisz',modal_import_action:'Importuj',modal_delete_action:'Usuń',modal_reset_all:'Resetuj wszystko',modal_delete_forever:'Usuń na zawsze',
    modal_export_title:'Eksportuj zapis',modal_export_body:'Skopiuj i przechowaj w bezpiecznym miejscu.',modal_import_title:'Importuj zapis',modal_import_body:'Wklej wyeksportowany zapis. Nadpisze obecny postęp.',modal_reset_title:'Resetować grę?',modal_reset_body:'To wymaże CAŁY postęp. Najpierw wyeksportuj.',modal_del_acc_title:'Usunąć konto?',modal_del_acc_body:'To trwale usunie twoje konto i cały postęp w chmurze. Nie można cofnąć.',modal_save_tpl_title:'Zapisz szablon',modal_save_tpl_body:'Podaj nazwę dla tego szablonu sesji:',modal_del_tpl_title:'Usunąć szablon?',modal_del_tpl_body:'Tej operacji nie można cofnąć.',modal_discard_pending_title:'Odrzucić zaplanowaną sesję?',modal_discard_pending_body:'Tej operacji nie można cofnąć.',modal_signin_title:'Zaloguj się / Utwórz konto',
    streak_hint:'Powtórz ćwiczenie w ciągu 7 dni, aby zdobyć bonus za regularność (+5% tygodniowo, maks. ×1,50). Pominięcie okna 7 dni resetuje bonus do ×1,00.',
    toast_imported:'Zapis zaimportowany.',toast_invalid:'Nieprawidłowe dane.',toast_invalid_save:'Nieprawidłowe dane zapisu.',toast_reset:'Gra zresetowana.',toast_shop_refresh:'Asortyment odświeżony.',toast_cloud_loaded:'Zapis z chmury wczytany.',toast_signed_in:'Zalogowano.',toast_signed_out:'Wylogowano.',toast_account_deleted:'Konto usunięte.',toast_synced:'Zsynchronizowano z chmurą.',toast_enter_credentials:'Podaj nazwę postaci i hasło.',toast_pass_short:'Hasło musi mieć co najmniej 6 znaków.',toast_name_taken:'Nazwa postaci jest już zajęta.',toast_tpl_saved:'Szablon zapisany.',toast_tpl_loaded:'Szablon wczytany.',toast_tpl_deleted:'Szablon usunięty.',toast_tpl_no_exercises:'Najpierw dodaj co najmniej jedno ćwiczenie.',toast_tpl_no_name:'Podaj nazwę szablonu.',toast_invalid_name:'Nieprawidłowa nazwa postaci.',toast_created:'Konto utworzone! Logowanie...',toast_signin_fail:'Logowanie nieudane: ',toast_signup_fail:'Rejestracja nieudana: ',toast_session_planned:'Sesja zaplanowana. Dokończ ją później, aby otrzymać nagrody.',toast_pending_discarded:'Zaplanowana sesja odrzucona.',reward_forge:'Kuźnia przyjmuje twój wysiłek.',reward_gold:'Złoto',reward_streak_bonus:'Bonus za serię',reward_weekly_title:'TYGODNIOWE ZADANIE UKOŃCZONE',reward_weekly_falls:'{boss} upada przed tobą!',reward_bonus_gold:'Dodatkowe złoto',reward_bonus_xp:'Dodatkowe PD',reward_streak:'Seria',reward_weeks:'tygodni',inv_req_lvl:'Wymag. poz.',stat_str_from:'SIŁ z ekwipunku',stat_dex_from:'ZRE z ekwipunku',stat_vit_from:'WIT z ekwipunku',stat_str_header:'SIŁ — Siła',stat_dex_header:'ZRE — Zręczność',stat_vit_header:'WIT — Witalność',stat_str_desc:'Każdy punkt dodaje <b>+1 obrażeń</b> do ataków. Budowany ciężkimi ćwiczeniami złożonymi — martwy ciąg, przysiady, wyciskanie, wiosłowanie.',stat_dex_desc:'Każdy punkt dodaje +1 do maks. obrażeń i zwiększa szansę na krit. Budowany pracą z masą ciała, podciąganiem, dipami, wypadami, izolacjami.',stat_vit_desc:'Każdy punkt dodaje <b>+{hpPerVIT} max HP</b> i redukuje obrażenia o procent (WIT÷(WIT+{vitDefenseK}), maks {vitDefenseMax}%). Budowany ćwiczeniami WIT lub serią z {vitRepThreshold}+ powtórzeniami.',ab_free:'Bezpłatnie',ab_stamina:'wytrzymałości',ab_unlocks_at:'Odblokuje na poz.',levelup_reached:'Osiągnąłeś poziom {level}.',levelup_new_ability:'Nowa zdolność: {name}',combat_face_boss:'Stajesz przed {boss}.',tooltip_equipped:'Wyposażone',tooltip_req_lv:'Wymag. poz.',
  },
};

export function t(key) {
  const lang = store.state?.tutorialLang || 'en';
  return (STRINGS[lang] && STRINGS[lang][key]) || STRINGS.en[key] || key;
}

export function exName(ex) {
  const lang = store.state?.tutorialLang || 'en';
  return (lang !== 'en' && ex.names && ex.names[lang]) ? ex.names[lang] : ex.name;
}
